### ISSUE TITLE
Files Upload API not working

### ISSUE THREAD

**Issue by derysdominguez** [FlatFilers/flatfile-node#58]
I get this error when trying to upload a file:
```
Client.js:150 Uncaught (in promise) TypeError: _request.getBoundary is not a function
    at Files.eval (Client.js:150:74)
    at Generator.next (<anonymous>)
    at fulfilled (Client.js:31:58)
```

**Comment by Arsik36** [comment]
Derys, can you share how you're making that request?

**Comment by derysdominguez** [comment]
@Arsik36 Thanks for your answer, here are more details of my code:
```
listener.on(
    "space:updated",
    async ({ context: { spaceId } }) => {
      await api.files.upload( file, {
        spaceId: spaceId,
        environmentId: environmentId,
      })
    }
  )
```

Basically what I'm trying to do is when the space is mounted, upload a file automatically to skip directly to the "Map Fields" step. Maybe I should take a different approach?

**Comment by damonbanks** [comment]
@derysdominguez I have confirmed that our node package for file uploading is working as expected and working on our end. your listener.on code looks correct assuming the file object is valid. 

Could you try the following:
1. Make sure you have the most recent version of the api
2. this code is working for me atm. 
```
try {
        if (!fs.existsSync(filePath)) {
            throw new Error(`File does not exist at path: ${filePath}`);
        }

        const fileStream = fs.createReadStream(filePath);

        const createFileRequest = {
            spaceId: process.env.FLATFILE_SPACE_ID,
            environmentId: process.env.FLATFILE_ENVIRONMENT_ID,
        };

        console.log('Uploading with configuration:', {
            spaceId: process.env.FLATFILE_SPACE_ID,
            environmentId: process.env.FLATFILE_ENVIRONMENT_ID,
            apiKeyPresent: !!process.env.FLATFILE_API_KEY
        });

        const response = await flatfile.files.upload(
            fileStream,
            createFileRequest
        );

        return response;
    } catch (error) {
        if (error.response?.status === 401) {
            throw new Error(`Authentication failed. Please verify your API key is correct and has the necessary permissions.`);
        }
        throw error;
    }
```

Let me know if you continue to have issue with the above.
